from tkinter import *
root = Tk()
root.title('ADHD BANK')
root.config(bg='red')
T = Label(root, text='ADHD BANK', font=("Bold",150),bg='red', fg='blue')
T.place(relx=0.5,rely=0.5,anchor='center')
T.pack()
L = Label(root, text='LOGIN' ,font=("Bold",40),fg='green',bg='red')
L.pack()
e=Entry(root,width=50)
e.pack()
e.insert(0,"Enter username or account number")
f=Entry(root,width=50)
f.pack()
f.insert(0,"Password")
bt1=Button(root, text="LOGIN",width=15,font=("Bold"))
bt1.pack()
G = Label(root, text='REGISTER', font=("Bold",35),fg='indigo',bg='red')
G.pack()
bt2=Button(root, text='Click here to register', width=20,font=("Bold"))
bt2.pack()
root.mainloop()